In [3]:
from google.colab import files
uploaded = files.upload()

Saving adult.csv to adult (1).csv
Saving Dataset of Diabetes .csv to Dataset of Diabetes .csv

In [4]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

In [6]:
import pandas as pd

diabetes_df = pd.read_csv("Dataset of Diabetes .csv")
diabetes_df.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

In [7]:
adult_df = pd.read_csv("adult (1).csv")
adult_df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [25]:
for col in diabetes_df.select_dtypes(include=np.number).columns:
    diabetes_df[col] = diabetes_df[col].fillna(diabetes_df[col].mean())

for col in adult_df.select_dtypes(include="object").columns:
    adult_df[col] = adult_df[col].fillna(adult_df[col].mode()[0])

In [27]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
cat_cols = ["gender", "class"]

for col in cat_cols:
    diabetes_df[col] = encoder.fit_transform(diabetes_df[col])

print("Categorical Data Encoded")

Categorical Data Encoded

In [28]:
def remove_outliers(data, col):
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return data[(data[col] >= lower) & (data[col] <= upper)]

for col in diabetes_df.select_dtypes(include=np.number):
    diabetes_df = remove_outliers(diabetes_df, col)

print("Outliers Removed")

Outliers Removed

In [29]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

df_minmax = diabetes_df.copy()

features = df_minmax.drop("class", axis=1)

df_minmax[features.columns] = minmax.fit_transform(features)

print("Min-Max Normalized Data:")
df_minmax.head()

Min-Max Normalized Data:

,id,no_pation,gender,age,urea,cr,hba1c,chol,tg,hdl,ldl,vldl,bmi,class
169,0.892231,0.631506,1.0,0.111111,0.333333,0.690476,0.234375,0.745455,0.772727,0.2,0.673469,0.80,0.15,2
170,0.106516,0.378450,0.0,0.296296,0.386667,0.404762,0.914062,0.436364,0.386364,0.4,0.387755,0.40,0.50,2
171,0.286967,0.141586,0.0,0.296296,0.386667,0.404762,0.914062,0.436364,0.386364,0.4,0.387755,0.40,0.50,2
172,0.630326,0.354890,0.0,0.222222,0.386667,0.190476,0.351562,0.436364,0.454545,0.6,0.326531,0.45,0.20,2
174,0.006266,0.631753,0.0,0.148148,0.253333,0.440476,0.242188,0.672727,0.795455,0.6,0.448980,0.80,0.25,2

In [30]:
from sklearn.preprocessing import StandardScaler

standard = StandardScaler()

df_standard = diabetes_df.copy()

features = df_standard.drop("class", axis=1)

df_standard[features.columns] = standard.fit_transform(features)

print("Standard Scaled Data:")
df_standard.head()

Standard Scaled Data:

,id,no_pation,gender,age,urea,cr,hba1c,chol,tg,hdl,ldl,vldl,bmi,class
169,1.567028,0.151012,0.933756,-2.424451,-0.607659,1.278854,-1.645408,1.167874,1.594532,-1.220438,1.334936,1.487580,-2.110406,2
170,-1.126422,-1.081969,-1.070943,-1.320212,-0.344872,-0.102125,2.016701,-0.395993,-0.157179,-0.313766,-0.066840,-0.277065,-0.424102,2
171,-0.507831,-2.236057,-1.070943,-1.320212,-0.344872,-0.102125,2.016701,-0.395993,-0.157179,-0.313766,-0.066840,-0.277065,-0.424102,2
172,0.669211,-1.196766,-1.070943,-1.761908,-0.344872,-1.137860,-1.014010,-0.395993,0.151947,0.592906,-0.367220,-0.056484,-1.869506,2
174,-1.470084,0.152212,-1.070943,-2.203603,-1.001839,0.070497,-1.603314,0.799905,1.697574,0.592906,0.233541,1.487580,-1.628605,2

In [31]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

cat_cols = adult_df.select_dtypes(include='object').columns

for col in cat_cols:
    adult_df[col] = encoder.fit_transform(adult_df[col])

print("Categorical Data Encoded")

Categorical Data Encoded

In [32]:
def remove_outliers(data, col):
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return data[(data[col] >= lower) & (data[col] <= upper)]

for col in adult_df.select_dtypes(include=np.number):
    adult_df = remove_outliers(adult_df, col)

print("Outliers Removed")

Outliers Removed

In [33]:
print(adult_df.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [34]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

adult_minmax = adult_df.copy()

features = adult_minmax.drop("income", axis=1)

adult_minmax[features.columns] = minmax.fit_transform(features)

print("Min-Max Normalized Data:")
adult_minmax.head()

Min-Max Normalized Data:

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
1,0.344262,0.0,0.187823,0.555556,0.363636,0.333333,0.307692,0.0,0.0,1.0,0.0,0.0,0.894737,0.0,0
8,0.114754,0.0,0.879030,1.000000,0.454545,0.666667,0.538462,0.8,0.0,0.0,0.0,0.0,0.368421,0.0,0
12,0.147541,0.0,0.168748,0.555556,0.363636,0.666667,0.000000,0.2,0.0,0.0,0.0,0.0,0.315789,0.0,0
24,0.131148,0.0,0.474659,0.333333,0.727273,0.333333,0.692308,0.0,0.0,1.0,0.0,0.0,0.368421,0.0,0
28,0.606557,0.0,0.211786,0.555556,0.363636,0.333333,0.153846,0.0,0.0,1.0,0.0,0.0,0.105263,0.0,0

In [35]:
from sklearn.preprocessing import StandardScaler

standard = StandardScaler()

adult_standard = adult_df.copy()

features = adult_standard.drop("income", axis=1)

adult_standard[features.columns] = standard.fit_transform(features)

print("Standard Scaled Data:")
adult_standard.head()

Standard Scaled Data:

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
1,0.227350,0.0,-1.024796,-0.133647,-0.656437,-0.378332,-0.368853,-1.028191,0.0,0.767726,0.0,0.0,2.285864,0.0,0
8,-0.987041,0.0,2.235821,1.490958,-0.074982,0.845990,0.350262,1.647341,0.0,-1.302548,0.0,0.0,-0.341293,0.0,0
12,-0.813556,0.0,-1.114778,-0.133647,-0.656437,0.845990,-1.327673,-0.359308,0.0,-1.302548,0.0,0.0,-0.604009,0.0,0
24,-0.900299,0.0,0.328290,-0.945950,1.669381,-0.378332,0.829672,-1.028191,0.0,0.767726,0.0,0.0,-0.341293,0.0,0
28,1.615224,0.0,-0.911756,-0.133647,-0.656437,-0.378332,-0.848263,-1.028191,0.0,0.767726,0.0,0.0,-1.654872,0.0,0